version: '3'
services:
  graphql:
    build: .
    expose:
      - 4000
    environment:
      VIRTUAL_PORT: 4000
      VIRTUAL_HOST: "${API_VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${API_LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${API_LETSENCRYPT_EMAIL}"
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      VIRTUAL_PORT: 4466
      VIRTUAL_HOST: "${PRISMA_VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${PRISMA_LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${PRISMA_LETSENCRYPT_EMAIL}"
      PRISMA_CONFIG: |
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        secret: "${PRISMA_SECRET}"
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~

networks:
  default:
    external:
      name: nginx-net